name: Build tag push

on:
  push:
    branches: ['main']

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: build
        run:
          docker build -t dzonia/colony-simulation:latest .
      - name: login
        run:
          docker login -u dzonia -p ${{ secrets.DOCKER_HUB_TOKEN }}
      - name: push
        run:
          docker push dzonia/colony-simulation:latest
  pull_and_run:
    runs-on: ubuntu-latest
    needs: build_and_push
    steps:
      - name: Deploy using ssh
        uses: appleboy/ssh-action@master
        with:
            host: ${{ secrets.HOST }}
            username: ${{ secrets.USERNAME }}
            password: ${{ secrets.KEY }}
            port: 22
            script: |
              docker stop $(docker ps -a -q)
              docker pull dzonia/colony-simulation:latest
      - name: run
        uses: addnab/docker-run-action@v3
        with:
            image: dzonia/colony-simulation:latest
            options: "-d"
            run: docker run -d dzonia/colony-simulation:latest
