name: Build tag push

on:
  push:
    branches: ['ducks']

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: build
        run:
          docker build -t dzonia/colony-simulation:latest .
      - name: login
        run:
          docker login -u dzonia -p ${{ secrets.DOCKER_HUB_TOKEN }}
      - name: push
        run:
          docker push dzonia/colony-simulation:latest
